### ISSUE TITLE
missing headers in wire_defs.h

### ISSUE THREAD

**Issue by m0rb** [iaddis/metalnes#1]
Hi,

It seems wire_defs.h is missing a couple headers necessary to build

```
/home/morb/build/metalnes/source/metalnes/wire_defs.h: In function ‘void metalnes::bbox_reset(metalnes::rect&)’:
/home/morb/build/metalnes/source/metalnes/wire_defs.h:67:17: error: ‘numeric_limits’ is not a member of ‘std’
```

I added <stdexcept> and <limits> to the file and it was able to build OK on Fedora 35 / x86_64 (gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9))
